name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 23.8.0

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0
        with:
          # Custom install command to use
          install-command: npm install --legacy-peer-deps


      - name: Electron Builder
        # You may pin to the exact commit or the version.
        # uses: paneron/action-electron-builder@14b133702d1b2e9749912051c43ed62b4afe56c8
        uses: paneron/action-electron-builder@v1.8.1
        with:
          # Whether to skip package manager install
          skip_package_manager_install: true
          # GitHub authentication token
          github_token: ${{ secrets.github_token }}
          # Name of the optional NPM build script which is executed before `electron-builder`
          build_script_name: build-all
          

